name: my first work flow
on:
  push:
    branches:
      - master

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: first hello steps
        run: echo "hello users"

  install-flask:
    needs: my-first-job
    runs-on: ubuntu-latest
    steps:
      - name: installing flask
        run: |
        sudo apt update
        sudo apt install python python-pip

      - name: printing 
        run: echo "python version is $(python --version)"

